# Generated by Django 4.0.5 on 2022-07-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.CharField(max_length=30)),
                ('grupo', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('juego', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('juego', models.CharField(max_length=30)),
                ('grupo', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Lideres',
            },
        ),
    ]
